/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kuxing_aacrecorder_Recorder */

#ifndef _Included_com_kuxing_aacrecorder_Recorder
#define _Included_com_kuxing_aacrecorder_Recorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuxing_aacrecorder_Recorder
 * Method:    initNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kuxing_aacrecorder_Recorder_initNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kuxing_aacrecorder_Recorder
 * Method:    releaseNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kuxing_aacrecorder_Recorder_releaseNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kuxing_aacrecorder_Recorder
 * Method:    startNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kuxing_aacrecorder_Recorder_startNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kuxing_aacrecorder_Recorder
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kuxing_aacrecorder_Recorder_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kuxing_aacrecorder_Recorder
 * Method:    getVolumnNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kuxing_aacrecorder_Recorder_getVolumnNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
